# git init
# git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
baseURL: "https://is0383kk.github.io/"
languageCode: "ja-jp"
canonifyurls: false # ウェブサイトのURL正規化無効
publishDir: "public" # 静的ファイルの出力先
title: "よしをのほーむぺーじ" # タイトル
pagination:
  pagerSize: 10 # 投稿の数を10posts / 1page
theme: "PaperMod"

enableEmoji: true # 絵文字有効
enableRobotsTXT: true
enableGitInfo: true

buildDrafts: false # 下書き記事対象外
buildFuture: false # 将来日付記事対象外
buildExpired: false # 期限切れ記事対象外

minify:
  disableXML: true # XMLファイル最小化無効
  minifyOutput: true # 出力ファイル最小化有効

languages:
  ja:
    languageName: "日本語"
    weight: 1
    menu:
      main:
        # - identifier: posts
        #   name: ブログ
        #   url: posts
        #   weight: 5
        # - identifier: tags
        #   name: タグ
        #   url: tags/
        #   weight: 10
        - identifier: profile
          name: プロフィール
          url: others/profile
          weight: 15
        - identifier: career
          name: 経歴
          url: others/career
          weight: 20
        - identifier: github
          name: GitHub
          url: https://github.com/is0383kk
          weight: 25
        - identifier: blog
          name: 技術ブログ（Zenn）
          url: https://zenn.dev/is0383kk
          weight: 30

params:
  env: production # 本番環境
  title: "よしをのほーむぺーじ"
  # description: "学んだ知識や技術をブログでアウトプットしています。プログラミング・AWS・データベースなど特定の技術分野に問わず幅広く発信しています。"
  keywords: [Yoshiwo, yoshiwo, is0383kk, IS0383KK, hugo, papermod, 技術ブログ]
  author: ["Yoshiwo"]
  images: ["profile.jpg"]
  DateFormat: "2006-01-02" # 日付フォーマット
  defaultTheme: auto # 画面モード
  disableThemeToggle: false # 画面モードの切り替え有効

  ShowReadingTime: false # 記事の読了時間表示
  ShowShareButtons: true # SNS共有ボタン表示
  ShowPostNavLinks: true # 記事間のナビゲーションリンク表示
  ShowBreadCrumbs: true # パンくずリスト表示
  ShowCodeCopyButtons: true # コードブロックのコピーボタン表示

  disableSpecial1stPost: true # 最初の記事を特別なスタイルで表示しない
  disableScrollToTop: false # ページ上にスクロールするボタン非表示
  comments: false # コメント
  hidemeta: false # メタ情報
  hideSummary: false # 記事要約
  hasCJKLanguage: true
  showtoc: true # 記事目次
  tocopen: false # 目次展開

  assets:
    favicon: "favicon.ico"
    # favicon16x16: "favicon-16x16.png"
    # favicon32x32: "favicon-32x32.png"
    # apple_touch_icon: "apple-touch-icon.png"
    # safari_pinned_tab: "safari-pinned-tab.svg"

  label:
    text: "🏠 よしをのほーむぺーじ"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # Profile mode有効
    title: "Yoshiwo🐈"
    subtitle: Sometimes engineer sometimes lazy
    imageUrl: "profile.jpg" # プロフィール画像
    imageWidth: 350
    imageHeight: 350
    imageTitle: Profile image

  socialIcons:
    - name: github
      url: "https://github.com/is0383kk"
    - name: email
      url: "mailto:is0383kk@gmail.com"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    disabled: true
    URL: "https://github.com/is0383kk/is0383kk.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: "vs2018"
    tabWidth: 4
